---
- name: Install prereqs
  hosts: all
  become: yes
  roles:
    - prereqs

- name: Kubernetes master node
  hosts: master
  become: yes
  roles:
    - k8s-master

- name: Kubernetes worker nodes
  hosts: worker
  become: yes
  roles:
    - k8s-worker