---
# Kubernetes
- name: Resetting Kubernetes master node
  shell: kubeadm reset -f

- name: Initialize Kuberentes master node
  shell: kubeadm init --pod-network-cidr={{ cidr }} --apiserver-advertise-address=172.42.42.100
  register: join_command

- name: Setup kubeconfig
  shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Add Flannel CNI
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Fetch kubeconfig
  shell: cat $HOME/.kube/config
  register: kubeconfig

- debug: msg="{{ join_command.stdout }}"
- debug: msg="{{ kubeconfig }}"