---
# Docker
- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

# Kubernetes
- name: Letting iptables see bridged traffic
  shell:
    cmd: |
      cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF

- name: Reload sysctl values
  shell: sysctl --syst

- name: Add Kubernetes GPG apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kuberenetes repository
  apt_repository:
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'

- name: Update apt and install kubeadm, kubelet and kubectl
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - kubeadm
    - kubelet
    - kubectl